// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS3bXC4P8Sljrrwq8cTylo8Ra5wXd4hkY',
    appId: '1:867961121796:web:9f493c63fbbda53aad1951',
    messagingSenderId: '867961121796',
    projectId: 'groceteria-2412a',
    authDomain: 'groceteria-2412a.firebaseapp.com',
    storageBucket: 'groceteria-2412a.appspot.com',
    measurementId: 'G-03NWGMS1ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQknZDzlOtWjdjrlA57l2v5L5mtEuNm8',
    appId: '1:867961121796:android:2fc083c18f5ba7c2ad1951',
    messagingSenderId: '867961121796',
    projectId: 'groceteria-2412a',
    storageBucket: 'groceteria-2412a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr8e8avFCJF2ALvH1v408ZPXWQY1Y-RJ8',
    appId: '1:867961121796:ios:e6d512fe10622fd2ad1951',
    messagingSenderId: '867961121796',
    projectId: 'groceteria-2412a',
    storageBucket: 'groceteria-2412a.appspot.com',
    iosClientId: '867961121796-uhd6as11lhmhqo1jbpcrl34drp99lqho.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr8e8avFCJF2ALvH1v408ZPXWQY1Y-RJ8',
    appId: '1:867961121796:ios:a13458b6aeb61139ad1951',
    messagingSenderId: '867961121796',
    projectId: 'groceteria-2412a',
    storageBucket: 'groceteria-2412a.appspot.com',
    iosClientId: '867961121796-948rlcb2aj9s0uq9p0bsudu77ttn3mtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceteria.RunnerTests',
  );
}
